from abc import ABC, abstractmethod

import pandas_ta as ta

class BaseStrategy(ABC):
    def __init__(self, config=None):
        self.name = self.__class__.__name__
        self.config = config or {}

    @abstractmethod
    def generate_signal(self, df):
        pass

class ScalpEmaRsi(BaseStrategy):
    def generate_signal(self, df):
        # 0. Safety Check
        if df.empty or len(df) < 50: 
            return None
            
        params = self.config.get("params", {})
        ema_fast_len = params.get("ema_fast", 9)
        ema_slow_len = params.get("ema_slow", 21)
        rsi_len = params.get("rsi_period", 14)
        
        # 1. Calculate Indicators
        # Using pandas_ta directly on the dataframe
        df.ta.ema(length=ema_fast_len, append=True)
        df.ta.ema(length=ema_slow_len, append=True)
        df.ta.ema(length=ema_slow_len, append=True)
        df.ta.rsi(length=rsi_len, append=True)
        df.ta.atr(length=14, append=True) # Calculate ATR for Stops
        
        # Columns names generated by pandas_ta are like 'EMA_9', 'EMA_21', 'RSI_14'
        fast_col = f"EMA_{ema_fast_len}"
        slow_col = f"EMA_{ema_slow_len}"
        rsi_col = f"RSI_{rsi_len}"
        atr_col = "ATRr_14"
        
        if fast_col not in df.columns or atr_col not in df.columns: return None

        # 2. Get latest values
        current_fast = df[fast_col].iloc[-1]
        prev_fast = df[fast_col].iloc[-2]
        current_slow = df[slow_col].iloc[-1]
        prev_slow = df[slow_col].iloc[-2]
        current_rsi = df[rsi_col].iloc[-1]
        close = df['close'].iloc[-1]
        atr = df[atr_col].iloc[-1]
        
        # 3. Logic: Crossover
        # BUY: Fast crosses ABOVE Slow
        if prev_fast <= prev_slow and current_fast > current_slow:
            if current_rsi < params.get("rsi_overbought", 70): # Filter
                return {
                    "signal": "BUY",
                    "sl": close - (1.5 * atr),
                    "tp": close + (3.0 * atr),
                    "comment": "EMA Crossover + RSI"
                }
                
        # SELL: Fast crosses BELOW Slow
        if prev_fast >= prev_slow and current_fast < current_slow:
            if current_rsi > params.get("rsi_oversold", 30):
                return {
                    "signal": "SELL",
                    "sl": close + (1.5 * atr),
                    "tp": close - (3.0 * atr),
                    "comment": "EMA Crossover + RSI"
                }
        return None

class InstitutionalScalp(BaseStrategy):
    def generate_signal(self, df):
        return None

class SwingTrendPullback(BaseStrategy):
    def generate_signal(self, df):
        if df.empty or len(df) < 200: return None
        
        params = self.config.get("params", {})
        ema_trend_len = params.get("ema_trend", 200)
        ema_fast_len = params.get("ema_pullback_fast", 20)
        ema_slow_len = params.get("ema_pullback_slow", 50)
        
        # 1. Indicators
        df.ta.ema(length=ema_trend_len, append=True)
        df.ta.ema(length=ema_fast_len, append=True)
        df.ta.ema(length=ema_slow_len, append=True)
        df.ta.rsi(length=14, append=True)
        df.ta.atr(length=14, append=True)
        
        trend_col = f"EMA_{ema_trend_len}"
        fast_col = f"EMA_{ema_fast_len}"
        slow_col = f"EMA_{ema_slow_len}"
        rsi_col = "RSI_14"
        atr_col = "ATRr_14"
        
        if trend_col not in df.columns: return None
        
        close = df['close'].iloc[-1]
        low = df['low'].iloc[-1]
        high = df['high'].iloc[-1]
        trend = df[trend_col].iloc[-1]
        ema_fast = df[fast_col].iloc[-1]
        ema_slow = df[slow_col].iloc[-1]
        rsi = df[rsi_col].iloc[-1]
        atr = df[atr_col].iloc[-1] if atr_col in df.columns else (close * 0.01)
        
        # LONG: Overall Trend Bullish (Price > EMA200)
        if close > trend:
            if low <= ema_fast and rsi > params.get("rsi_min_long", 40):
                 return {
                    "signal": "BUY",
                    "sl": close - (2.0 * atr),
                    "tp": close + (5.0 * atr),
                    "comment": "Trend Pullback"
                }

        # SHORT: Overall Trend Bearish (Price < EMA200)
        if close < trend:
            if high >= ema_fast and rsi < params.get("rsi_max_short", 60):
                return {
                    "signal": "SELL",
                    "sl": close + (2.0 * atr),
                    "tp": close - (5.0 * atr),
                    "comment": "Trend Pullback"
                }
        return None

class DayTradingORB(BaseStrategy):
    def generate_signal(self, df):
        # Requires intraday data with timestamps
        if df.empty: return None
        
        # Calculate VWAP
        df.ta.vwap(append=True) # VWAP requires volume, high, low, close
        df.ta.atr(length=14, append=True)
        if 'VWAP_D' not in df.columns: return None
        
        vwap = df['VWAP_D'].iloc[-1]
        close = df['close'].iloc[-1]
        
        # Simplified ORB Logic (Session agnostic for now, just takes last N candles as "Range" if implied)
        # Real ORB needs specific time of day. 
        # Assuming we run this live during the session.
        # Check breakout of previous High/Low?
        
        # For this iteration, we implemented a simple VWAP Trend Follow
        if close > vwap:
            atr = df['ATRr_14'].iloc[-1] if 'ATRr_14' in df.columns else (close * 0.01)
            return {
                "signal": "BUY",
                "sl": close - atr,
                "tp": close + (2 * atr),
                "comment": "VWAP Trend"
            }
        elif close < vwap:
            atr = df['ATRr_14'].iloc[-1] if 'ATRr_14' in df.columns else (close * 0.01)
            return {
                "signal": "SELL",
                "sl": close + atr,
                "tp": close - (2 * atr),
                "comment": "VWAP Trend"
            }
            
        return None

class MeanReversion(BaseStrategy):
    def generate_signal(self, df):
        return None

class SMCFVG(BaseStrategy):
    def generate_signal(self, df):
        return None
