#!/usr/bin/env python3
"""
Strategy Signal Analysis - See which strategies generate signals
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from strategies.engine import StrategyEngine
from app.core.risk_manager import RiskManager
import pandas as pd

# Load historical data
df = pd.read_csv("data/historical/BTC_15m.csv")
df['timestamp'] = pd.to_datetime(df['timestamp'])

print("="*60)
print("🔍 STRATEGY SIGNAL ANALYSIS")
print("="*60)
print(f"📊 Data: {len(df)} candles")
print(f"📅 Period: {df['timestamp'].iloc[0]} → {df['timestamp'].iloc[-1]}")
print()

# Create engine
risk_manager = RiskManager()
engine = StrategyEngine(risk_manager)

# Track signals by strategy
signal_counts = {}

# Analyze every 10th candle (to speed up)
for i in range(100, len(df), 10):
    df_slice = df.iloc[:i+1].copy()
    
    try:
        result = engine.analyze(df_slice)
        
        if result.get('signals'):
            for signal in result['signals']:
                strat_name = signal.get('strategy', 'Unknown')
                signal_counts[strat_name] = signal_counts.get(strat_name, 0) + 1
                
                # Print first signal from each strategy
                if signal_counts[strat_name] == 1:
                    print(f"✅ {strat_name}: First signal at candle {i}")
                    print(f"   Side: {signal['signal']}, Price: {signal['price']:.2f}")
                    print(f"   SL: {signal['sl']:.2f}, TP: {signal['tp']:.2f}")
                    print()
    except Exception as e:
        if i == 100:  # Only print first error
            print(f"⚠️ Error at candle {i}: {e}")

print("="*60)
print("📊 SIGNAL SUMMARY")
print("="*60)

if signal_counts:
    for strat, count in sorted(signal_counts.items(), key=lambda x: x[1], reverse=True):
        print(f"{strat:<30} {count:>5} signals")
else:
    print("❌ NO SIGNALS GENERATED BY ANY STRATEGY")
    print("\nPossible causes:")
    print("- Market conditions don't match strategy criteria")
    print("- Strategies require specific regime (TREND/RANGE)")
    print("- Entry conditions too strict")

print("="*60)
