# Global Constants for NovaBot

# Market Analysis
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
RSI_HARD_SELL_THRESHOLD = 25  # Below this, don't SELL (already too low)
RSI_HARD_BUY_THRESHOLD = 75   # Above this, don't BUY (already too high)

# Timeframes
TIMEFRAME_1M = "1m"
TIMEFRAME_15M = "15m"

# Execution & Risk
DEFAULT_LEVERAGE = 5
DEFAULT_SIZE_USDC = 20.0
FALLBACK_STOP_LOSS_PCT = 0.025 # 2.5%
FALLBACK_TAKE_PROFIT_PCT = 0.04  # 4%
AI_CONFIDENCE_THRESHOLD = 75
TP_SL_RECALIBRATION_THRESHOLD_PCT = 0.005  # 0.5% tolerance

# Loop Intervals (Seconds)
TRADING_LOOP_INTERVAL = 30
ERROR_SLEEP_INTERVAL = 10
AI_MARKET_ANALYSIS_INTERVAL_MIN = 15
AI_POSITION_ANALYSIS_INTERVAL_MIN = 5

# Regimes
REGIME_TREND_BULL_STRONG = "TREND_BULL_STRONG"
REGIME_TREND_BEAR_STRONG = "TREND_BEAR_STRONG"

# Feature Flags
GAMIFICATION_ENABLED = True
